# Generated by Django 4.1.3 on 2022-11-07 16:03

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True)),
                ('desc', models.TextField(blank=True, max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('photo', models.ImageField(upload_to=main_page.models.Events.get_file_name)),
                ('is_visible', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
