# Generated by Django 4.1.3 on 2022-11-08 21:28

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0002_events'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to=main_page.models.Gallery.get_file_name, verbose_name='Завантажити фото')),
            ],
            options={
                'verbose_name': 'Галерея фото',
                'verbose_name_plural': 'Галерея фото',
            },
        ),
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва презентації')),
                ('desc', models.TextField(blank=True, max_length=500, verbose_name='Опис')),
                ('photo', models.ImageField(upload_to=main_page.models.Presentation.get_file_name, verbose_name='Завантажити фото')),
                ('video', models.URLField(verbose_name='Завантажити відео')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображати')),
                ('why_us', models.BooleanField(default=True, verbose_name='Розділ "Чому ми"')),
            ],
            options={
                'verbose_name': 'Презентація',
                'verbose_name_plural': 'Презентації',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['position'], 'verbose_name': 'Категорія меню', 'verbose_name_plural': 'Категорії меню'},
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['position'], 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Презентація', 'verbose_name_plural': 'Презентації'},
        ),
        migrations.AlterField(
            model_name='category',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відображати'),
        ),
        migrations.AlterField(
            model_name='category',
            name='position',
            field=models.PositiveSmallIntegerField(unique=True, verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва категорії'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='desc',
            field=models.TextField(blank=True, max_length=500, verbose_name='Опис страви'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='ingredients',
            field=models.CharField(max_length=100, verbose_name='Інгредієнти'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_special',
            field=models.BooleanField(default=False, verbose_name='Спеціальна пропозиція'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відображати'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.Dish.get_file_name, verbose_name='Завантажити фото'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='position',
            field=models.PositiveSmallIntegerField(verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Ціна'),
        ),
        migrations.AlterField(
            model_name='dish',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва страви'),
        ),
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, verbose_name='Дата та час події'),
        ),
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.TextField(blank=True, max_length=500, verbose_name='Опис події'),
        ),
        migrations.AlterField(
            model_name='events',
            name='is_visible',
            field=models.BooleanField(default=True, verbose_name='Відображати'),
        ),
        migrations.AlterField(
            model_name='events',
            name='photo',
            field=models.ImageField(upload_to=main_page.models.Events.get_file_name, verbose_name='Завантажити фото'),
        ),
        migrations.AlterField(
            model_name='events',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Вартість'),
        ),
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Назва події'),
        ),
    ]
