# Generated by Django 4.1.3 on 2022-11-10 13:55

from django.db import migrations, models
import main_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0003_gallery_presentation_alter_category_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Призвище')),
                ('job_title', models.CharField(max_length=20, verbose_name='Посада')),
                ('photo', models.ImageField(upload_to=main_page.models.Chefs.get_file_name, verbose_name='Завантажити фото')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображати')),
            ],
            options={
                'verbose_name': 'Кухар',
                'verbose_name_plural': 'Кухарі',
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(db_index=True, max_length=20, verbose_name='Вулиця та будинок')),
                ('city', models.CharField(max_length=20, verbose_name='Місто')),
                ('start_day', models.DateField(blank=True, verbose_name='Працюємо з (день тижня)')),
                ('end_day', models.DateField(blank=True, verbose_name='Працюємо по (день тижня)')),
                ('start_time', models.TimeField(blank=True, verbose_name='Відкриваємось о (час)')),
                ('close_time', models.TimeField(blank=True, verbose_name='Закриваємось о (час)')),
                ('email_1', models.EmailField(blank=True, max_length=254, verbose_name='Імейл_1')),
                ('email_2', models.EmailField(max_length=254, verbose_name='Імейл_2')),
                ('phone_1', models.CharField(blank=True, max_length=13, verbose_name='Телефон_1')),
                ('phone_2', models.CharField(max_length=13, verbose_name='Телефон_2')),
            ],
            options={
                'verbose_name': 'Інформація про ресторан',
                'verbose_name_plural': 'Інформація про ресторан',
            },
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=20, verbose_name="Ім'я")),
                ('surname', models.CharField(max_length=20, verbose_name='Призвище')),
                ('profession', models.CharField(max_length=30, verbose_name='Професія')),
                ('photo', models.ImageField(upload_to=main_page.models.Testimonials.get_file_name, verbose_name='Завантажити фото')),
                ('text', models.TextField(blank=True, max_length=500, verbose_name='Відгук')),
                ('is_visible', models.BooleanField(default=True, verbose_name='Відображати')),
            ],
            options={
                'verbose_name': 'Відгук',
                'verbose_name_plural': 'Відгуки',
            },
        ),
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['category', 'position'], 'verbose_name': 'Страва', 'verbose_name_plural': 'Страви'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Подія', 'verbose_name_plural': 'Події'},
        ),
        migrations.AddField(
            model_name='presentation',
            name='about',
            field=models.BooleanField(default=False, verbose_name='Розділ "Про нас"'),
        ),
        migrations.AddField(
            model_name='presentation',
            name='greetings',
            field=models.BooleanField(default=False, verbose_name='Розділ "Вітання від ресторану"'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='photo',
            field=models.ImageField(blank=True, upload_to=main_page.models.Presentation.get_file_name, verbose_name='Завантажити фото'),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='video',
            field=models.URLField(blank=True, verbose_name='Завантажити відео'),
        ),
    ]
