# Generated by Django 4.1.3 on 2022-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0006_alter_information_email_1_alter_information_phone_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Імейл_1'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone_1',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='Телефон_1'),
        ),
    ]
