# Generated by Django 4.1.3 on 2022-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_alter_information_email_1_alter_information_phone_1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='email_1',
            field=models.EmailField(default='', max_length=254, verbose_name='Імейл_1'),
        ),
        migrations.AlterField(
            model_name='information',
            name='email_2',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Імейл_2'),
        ),
        migrations.AlterField(
            model_name='information',
            name='end_day',
            field=models.DateField(blank=True, verbose_name='Працюємо по (день тижня)'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone_1',
            field=models.CharField(default='', max_length=13, verbose_name='Телефон_1'),
        ),
        migrations.AlterField(
            model_name='information',
            name='phone_2',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='Телефон_2'),
        ),
        migrations.AlterField(
            model_name='information',
            name='start_day',
            field=models.DateField(blank=True, verbose_name='Працюємо з (день тижня)'),
        ),
    ]
