# Generated by Django 4.1.3 on 2022-11-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0009_alter_information_end_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Опис'),
        ),
    ]
