# Generated by Django 4.1.3 on 2022-11-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0010_alter_presentation_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='desc',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Опис події'),
        ),
    ]
