# Generated by Django 4.1.3 on 2022-11-16 16:10

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ваше ім'я")),
                ('persons', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Кількість людей')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Невірний формат номеру телефону', regex='^[+]?380\\d{2}([ -])?\\d{7}$')], verbose_name='Ваш телефон')),
                ('message', models.TextField(default='', max_length=500, verbose_name='Залиште повідомлення')),
                ('email', models.CharField(default='', max_length=50, validators=[django.core.validators.EmailValidator(message='Введіть вірний e-mail')], verbose_name='Ваш імейл')),
                ('date_reserve', models.DateField(default=datetime.date(2022, 11, 16), verbose_name='Оберіть дату')),
                ('time_reserve', models.TimeField(blank=True, null=True, verbose_name='Оберіть час')),
                ('is_processed', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_in',),
            },
        ),
    ]
