# Generated by Django 4.1.3 on 2022-11-17 15:16

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name="Ваше ім'я")),
                ('email', models.CharField(default='', max_length=50, validators=[django.core.validators.EmailValidator(message='Введіть вірний e-mail')], verbose_name='Ваш імейл')),
                ('subject', models.CharField(default='Testimonial', max_length=50, verbose_name='Тема повідомлення')),
                ('message', models.TextField(default='', max_length=500, verbose_name='Залиште повідомлення')),
                ('is_processed', models.BooleanField(default=False)),
                ('date_in', models.DateTimeField(auto_now_add=True)),
                ('date_modify', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-date_in',),
            },
        ),
        migrations.AlterField(
            model_name='userreservation',
            name='date_reserve',
            field=models.DateField(default=datetime.date(2022, 11, 17), verbose_name='Оберіть дату'),
        ),
    ]
